# -*- coding: utf-8 -*-
"""2003a52028_mse

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1abrrjgSF7isXczhR4_ZQBU83skgJ5Di_
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/grive')

import matplotlib.pyplot as plt

x = [3.2,3.2,3.7,3.9,4,4,4.1,4.5,4.9,5.1,5.3,5.9,6]
y = [54445,64445,57189,63218,55794,56957,57081,61111,67938,66029,83088,81363,93940]

plt.scatter(x,y)
plt.show()

import numpy as np
x1=[3.2,3.2,3.7,3.9,4,4,4.1,4.5,4.9,5.1,5.3,5.9,6]
y=[54445,64445,57189,63218,55794,56957,57081,61111,67938,66029,83088,81363,93940]
yp=[]
e=[]
m=[1235,1500,1850,2000]
c=[1900,1950,2000,2100]
def linear(m,c):
  sum=0
  for i in range(0,len(x1)):
    yp.append(m*x1[i]+c)
    g=(y[i]-yp[i])**2
    sum=sum+g
    e.append(g)
    print('Mean square error is :',np.mod(sum,len(x1)))
    sum=0    
for i in range(0,1):
   linear(m[i],c[i])